### ISSUE TITLE
org.apache.http.Header is missing in android M

### ISSUE THREAD

**Issue by luminousman** [loopj/android-async-http#927] opened 2015-08-18 10:04 UTC

**Comment by luminousman** [comment] 2015-08-18 10:05
![capture](https://cloud.githubusercontent.com/assets/1277011/9327471/b252a57e-45be-11e5-85df-388f9615dd02.PNG)

**Comment by luminousman** [comment] 2015-08-18 10:09
https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client

**Comment by smarek** [comment] 2015-08-24 08:29
Closing as dupe of #830

**Closed by smarek** 2015-08-24 08:29 UTC
