### ISSUE TITLE
Did something change in 1.4.7 without a new release tag?

### ISSUE THREAD

**Issue by cpiggott** [loopj/android-async-http#1011] opened 2015-10-27 20:14 UTC
Hello,

I was running 1.4.7 on an application that I was building and making a call to the Google Places API without any problems.

Randomly one day, the API stopped working. At first I thought it was something with my API access or tokens, but everything on that side was working fine as I was able to make the same call from POSTman without issue.

I updated to 1.4.9 and the call is still not working, while debugging I have found that JSON is being returned from the call, but none of the 'onSuccess' or 'onFailure' calls are being triggered.

Any help or information would be appreciated!

Thanks

**Comment by smarek** [comment] 2015-11-17 16:40
Well any info from you would be appreciated, because saying `it stopped working` is not going to help us debug this problem. Did you solve the issue since ? If not could you please provide example code which reproduces the issue? Closing as `on hold` until you provide more info. Thanks

**Closed by smarek** 2015-11-17 16:40 UTC
