### ISSUE TITLE
why bytesWritten > totalSize  ?

### ISSUE THREAD

**Issue by vagrant1991** [loopj/android-async-http#1009] opened 2015-10-23 16:32 UTC
487 22785-22785/com.seeyon.cmp D/CordovaWebViewImpl: onPageFinished(file:///android_asset/www/test/apps/demo/pagings/Component/download.html)
10-24 00:24:21.387 22785-22925/com.seeyon.cmp W/PluginManager: THREAD WARNING: exec() call to DownLoadPlugin.download blocked the main thread for 23ms. Plugin should use CordovaInterface.getThreadPool().
10-24 00:24:21.567 22785-22925/com.seeyon.cmp V/AsyncHttpRH: Progress 1088 from 2005 (54%)
10-24 00:24:21.567 22785-22925/com.seeyon.cmp V/AsyncHttpRH: Progress 2234 from 2005 (111%)
10-24 00:24:21.567 22785-22925/com.seeyon.cmp V/AsyncHttpRH: Progress 3751 from 2005 (187%)
10-24 00:24:21.567 22785-22925/com.seeyon.cmp V/AsyncHttpRH: Progress 4988 from 2005 (249%)
10-24 00:24:21.567 22785-22925/com.seeyon.cmp V/AsyncHttpRH: Progress 5441 from 2005 (271%)

FileAsyncHttpResponseHandler  onProgress method :

public void onProgress(long bytesWritten, long totalSize) {
                super.onProgress(bytesWritten, totalSize);
} 

for some reaseon i want to check if bytesWritten == totalSize, but it seems bytesWritten can larger than totalSize.

**Comment by smarek** [comment] 2015-11-17 16:38
There is something wrong with info, closing as duplicate of #957

**Closed by smarek** 2015-11-17 16:38 UTC
