### ISSUE TITLE
Synchronous ResponseHandler used in AsyncHttpClient.

### ISSUE THREAD

**Issue by HxRoy** [loopj/android-async-http#849] opened 2015-04-30 02:00 UTC
When I use AsyncHttpClient, it cause the following issues."Synchronous ResponseHandler used in AsyncHttpClient. You should create your response handler in a looper thread or use SyncHttpClient instead."
is that means I need use the SyncHttpClient ?

**Comment by smarek** [comment] 2015-07-12 11:17
Closing as duplicate of #828

**Closed by smarek** 2015-07-12 11:17 UTC
