### ISSUE TITLE
android sdks 6.0 can not support this lib

### ISSUE THREAD

**Issue by jelychow** [loopj/android-async-http#943] opened 2015-08-30 10:26 UTC
the latest android 6.0(sdks 23) has disable http conection which base on apache client;
we need your help

**Comment by Saren-Arterius** [comment] 2015-08-30 10:42
I think there is a lot of dup issues
https://github.com/loopj/android-async-http/issues?q=is%3Aissue+is%3Aclosed

**Comment by smarek** [comment] 2015-09-02 11:33
Yes, this is duplicate of #830

**Closed by smarek** 2015-09-02 11:33 UTC
