### ISSUE TITLE
Apache Header not found after updating to appcompat v23

### ISSUE THREAD

**Issue by mohd-bh** [loopj/android-async-http#935] opened 2015-08-24 22:06 UTC
When I updated to 'com.android.support:appcompat-v7:23.0.0'
class org.apache.http.Header is not found

the only solution was to change it back to 'com.android.support:appcompat-v7:22.2.1'

**Comment by smarek** [comment] 2015-08-25 04:20
Duplicate of #830

**Closed by smarek** 2015-08-25 04:20 UTC
