### ISSUE TITLE
Minor bug : invalid warning

### ISSUE THREAD

**Issue by neoteknic** [loopj/android-async-http#828] opened 2015-03-17 13:33 UTC
Hello, when I use a SyncHttpClient, on post I have a warning : 
```
W/AsyncHttpResponseHandler﹕ Current thread has not called Looper.prepare(). Forcing synchronous mode.
```

Of course it's a syncronous mode, because of SyncHttpClient,
please dont show this warning in the next version.

**Comment by smarek** [comment] 2015-04-02 13:05
From implementation, this warning is shown only if you use the library incorectly, 

you're probably somewhere calling `setUseSynchronousMode(false)` 
```
@Override
    public void setUseSynchronousMode(boolean sync) {
        // A looper must be prepared before setting asynchronous mode.
        if (!sync && looper == null) {
            sync = true;
            Log.w(LOG_TAG, "Current thread has not called Looper.prepare(). Forcing synchronous mode.");
        }

        // If using asynchronous mode.
        if (!sync && handler == null) {
            // Create a handler on current thread to submit tasks
            handler = new ResponderHandler(this, looper);
        } else if (sync && handler != null) {
            // TODO: Consider adding a flag to remove all queued messages.
            handler = null;
        }

        useSynchronousMode = sync;
    }
```

**Comment by neoteknic** [comment] 2015-04-02 17:58
Hello,
I dont call this method,my code is  : 

on the constructor :
SyncHttpClient httpClient = new SyncHttpClient();
PersistentCookieStore myCookieStore = new PersistentCookieStore(context);

httpClient.setCookieStore(myCookieStore);
httpClient.setUserAgent("Android");

on the run method of a Thread

RequestParams params = new RequestParams();
///.... ( I add some params here)
httpClient.post(context.getString(R.string.url_api), params, new JsonHttpResponseHandler() {
...


I cant use httpClient.setUseSynchronousMode(true), you can't use it in SyncHttpClient .

**Comment by neoteknic** [comment] 2015-04-02 18:06
I think that because I use the httpClient in a Thread, something trigger the Async mode somewhere.

**Comment by neoteknic** [comment] 2015-04-02 18:26
Tryed this : 
JsonHttpResponseHandler jrep=new JsonHttpResponseHandler() { ... }
jrep.setUseSynchronousMode(true);
httpClient.post(context.getString(R.string.url_api), params,jrep) ;
I still have the error... This is strange.
I think that the problem is in AsyncHttpResponseHandler

// Use asynchronous mode by default.
setUseSynchronousMode(false);

**Comment by smarek** [comment] 2015-04-03 11:03
You cannot use Synchronous mode if you run the SyncHttpClient on UI Thread (eg. directly in Activity or Fragment implementation). So if the current thread is UI Thread, AAH will automatically switch to async mode, and if you use SyncHttpClient it will trigger this warning message.

Also I've tried the implementation in Sample application (https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/SynchronousClientSample.java) which works as intended.

Please run the Sample application and try if it triggers the message on your device.
Also do you use release 1.4.6 or dev version 1.4.7 ?

**Comment by neoteknic** [comment] 2015-04-03 19:26
It dont run on UI thread, It run on my Webservice , it's a Thread class, the execution post is in the run method, but the declaration of SyncHttp is in the constructor so I think I have to move this in the run() method of the Thread.

I use the 1.4.6 found in gradle.

Thank You I will try .

De : Marek Sebera [mailto:notifications@github.com] 
Envoyé : vendredi 3 avril 2015 13:04
À : loopj/android-async-http
Cc : neoteknic
Objet : Re: [android-async-http] Minor bug : invalid warning (#828)

 

You cannot use Synchronous mode if you run the SyncHttpClient on UI Thread (eg. directly in Activity or Fragment implementation). So if the current thread is UI Thread, AAH will automatically switch to async mode, and if you use SyncHttpClient it will trigger this warning message.

Also I've tried the implementation in Sample application (https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/SynchronousClientSample.java) which works as intended.

Please run the Sample application and try if it triggers the message on your device.
Also do you use release 1.4.6 or dev version 1.4.7 ?

**Comment by neoteknic** [comment] 2015-04-03 19:39
Same problem with the httpClient created and called in a Thread : 

My class is :

Public Webservice extends Thread {

                …

 

                @Override

                public void run() {

                               Log.d("HTTP", "init:" + ACTION);

                               //This part was in the constructor before but I moved it here, httpClient was a private var, now it's a local var, but same warning.

                               SyncHttpClient httpClient = new SyncHttpClient();

                               PersistentCookieStore myCookieStore = new PersistentCookieStore(context);

                               httpClient.setCookieStore(myCookieStore);

                               httpClient.setUserAgent("Android");

                               //End of the part wich was in the constructor

 

                               RequestParams params = new RequestParams();

                               try {

                                               httpClient.post(context.getString(R.string.url_api), params, new JsonHttpResponseHandler() {

                                                               …. onSuccess onFailure …

                                               }

}

…

                

}

 

The Webservice class is generally called with the UI thread on a Fragment creation or in a onClick method.

This but is just a warning and have absolutly no other bad effect in my app, I will try the 1.4.7 

Thank you.

 

De : Marek Sebera [mailto:notifications@github.com] 
Envoyé : vendredi 3 avril 2015 13:04
À : loopj/android-async-http
Cc : neoteknic
Objet : Re: [android-async-http] Minor bug : invalid warning (#828)

 

You cannot use Synchronous mode if you run the SyncHttpClient on UI Thread (eg. directly in Activity or Fragment implementation). So if the current thread is UI Thread, AAH will automatically switch to async mode, and if you use SyncHttpClient it will trigger this warning message.

Also I've tried the implementation in Sample application (https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/SynchronousClientSample.java) which works as intended.

Please run the Sample application and try if it triggers the message on your device.
Also do you use release 1.4.6 or dev version 1.4.7 ?

**Comment by smarek** [comment] 2015-04-04 18:14
How do you run the Thread? Because doing
```java
Webservice thread = new Webservice();
thread.run();
```
won't run the thread as separate, you have to call `thread.start()` to fork the thread in background.
Also you could try using AsyncTask for this

**Comment by neoteknic** [comment] 2015-04-05 10:23
Hello,
Yes of course I use the start method.
If I use run is crash the app ^^, of course it's a common mistake.

Webservice ws = new Webservice(getActivity());
ws.setAction("login");
ws.setListener(this);
ws.putParam("email",email);
ws.putParam("pass",password);
ws.start();

This is an example executed onCreate or on click in a Fragment (not in a
support v4 Fragment). All Fragments implement a
notifyOnThreadCompleteListener called when the thread end.
Can try with AsyncTask but have to modify a lot of code. This minor bug
just write a warning but have not other effect.

**Comment by smarek** [comment] 2015-04-05 15:40
Could you please test with latest 1.4.7 snapshot, so we can verify the issue still exists? 
To use, set Gradle config like this:

```gradle
repositories {
  maven {
    url "https://oss.sonatype.org/content/repositories/snapshots/"
  }
}

dependencies {
  compile "com.loopj.android:android-async-http:1.4.7-SNAPSHOT"
}
```

**Comment by neoteknic** [comment] 2015-04-09 18:45
Same problem with the 1.4.7 snapshot,
just this warning but no error / crash.

**Comment by smarek** [comment] 2015-05-09 15:20
I've just looked more into this. If you run [the sample](https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/SynchronousClientSample.java), you won't get the error mentioned in this ticket.
This sample uses approach I mentioned in https://github.com/loopj/android-async-http/issues/828#issuecomment-89632656
```java
new Thread(new Runnable() {
  @Override
  public void run() {
    Log.d(LOG_TAG, "Before Request");
    client.get(SynchronousClientSample.this, URL, headers, null, responseHandler);
    Log.d(LOG_TAG, "After Request");
  }
}).start();
```

This is done in the Activity, so I consider this not a problem. See the sample code for reference.
If you do this from Service/IntentService, see another sample [IntentServiceSample](https://github.com/loopj/android-async-http/blob/master/sample/src/main/java/com/loopj/android/http/sample/IntentServiceSample.java)

Lower are my logs, where there is no such error as mentioned in original question, you can run the Samples (or whole Sample application) and compare your logs to mine.

Logs from first sample `SynchronousClientSample`:
```
05-09 17:18:46.130  20960-15840/com.loopj.android.http.sample D/SyncSample﹕ Before Request
05-09 17:18:52.920  20960-15840/com.loopj.android.http.sample V/AsyncHttpResponseHandler﹕ Progress 240 from 240 (100%)
05-09 17:18:52.924  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Return Headers:
05-09 17:18:52.924  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Server : nginx
05-09 17:18:52.924  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Date : Sat, 09 May 2015 15:18:54 GMT
05-09 17:18:52.924  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Content-Type : application/json
05-09 17:18:52.925  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Content-Length : 240
05-09 17:18:52.925  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Connection : keep-alive
05-09 17:18:52.925  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Access-Control-Allow-Origin : *
05-09 17:18:52.925  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Access-Control-Allow-Credentials : true
05-09 17:18:52.929  20960-15840/com.loopj.android.http.sample D/SyncSample﹕ After Request
05-09 17:18:52.935  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Return Status Code: 200
05-09 17:18:52.938  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ Response data:
05-09 17:18:52.938  20960-20960/com.loopj.android.http.sample D/SyncSample﹕ {
    "args": {},
    "data": "",
    "files": {},
    "form": {},
    "headers": {
    "Accept-Encoding": "gzip",
    "Content-Length": "0",
    "Host": "httpbin.org"
    },
    "origin": "77.87.241.77",
    "url": "https://httpbin.org/delay/6"
    }
```

Logs from `IntentServiceSample`:
```
05-09 16:16:39.058  20960-20970/com.loopj.android.http.sample I/art﹕ Debugger is no longer active
05-09 16:57:35.143  20960-20970/com.loopj.android.http.sample I/art﹕ Debugger is no longer active
05-09 17:18:00.089  20960-20960/com.loopj.android.http.sample D/ExampleIntentService:IntentServiceSample﹕ onStart()
05-09 17:18:00.091  20960-15506/com.loopj.android.http.sample D/ExampleIntentService:IntentServiceSample﹕ onStart
05-09 17:18:00.774  20960-15506/com.loopj.android.http.sample V/AsyncHttpResponseHandler﹕ Progress 190 from 190 (100%)
05-09 17:18:00.779  20960-15506/com.loopj.android.http.sample D/ExampleIntentService:IntentServiceSample﹕ onSuccess
05-09 17:18:00.782  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Return Status Code: 200
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Return Headers:
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Server : nginx
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Date : Sat, 09 May 2015 15:18:02 GMT
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Content-Type : application/json
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Content-Length : 190
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Connection : keep-alive
05-09 17:18:00.786  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Access-Control-Allow-Origin : *
05-09 17:18:00.787  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Access-Control-Allow-Credentials : true
05-09 17:18:00.789  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ Response data:
05-09 17:18:00.789  20960-20960/com.loopj.android.http.sample D/IntentServiceSample﹕ {
    "args": {},
    "headers": {
    "Accept-Encoding": "gzip",
    "Content-Length": "0",
    "Host": "httpbin.org"
    },
    "origin": "77.87.241.77",
    "url": "https://httpbin.org/get"
    }
05-09 17:18:00.794  20960-15506/com.loopj.android.http.sample D/ExampleIntentService:IntentServiceSample﹕ onFinish
```

**Comment by smarek** [comment] 2015-05-09 15:21
@neoteknic please provide more info and test Sample application with your device/emulator, I'm putting this question on hold and moving to next milestone, as I cannot simulate the issue.

**Closed** 2015-07-12 12:18 UTC
Labels: on hold, question

**Comment by mpj** [comment] 2015-12-26 10:39
I'm getting this warning too. I'm calling SyncHttpClient inside onRunTask of a GcmTaskService, if that helps debug it. 
Nothing fancy, just a 
SyncHttpClient client = new SyncHttpClient();
ByteArrayEntity entity = // some data
client.post(this, "http://service.com/endpoint", entity, "application/json", resonseHandler)

**Comment by mylady** [comment] 2016-03-07 11:32
hi,
i'm getting this warning in 1.4.9
i just use SyncHttpClient in a TimerTask to peroidically post something to server and has nothing to do
with ui thread

`HttpClient.post(this, SpecificationSettings.DiscoveryApiProduct, jsonEntity, "application/json",null)`

**Comment by manjia** [comment] 2017-05-25 14:41
I also confirm this definitely happens even on 1.4.9, my senario can be summarized into running an AsynHttpClient with an AsyncHttpResponseHandler inside a background thread.
