### ISSUE TITLE
a url's response may be replaced by another url

### ISSUE THREAD

**Issue by ff0o0** [loopj/android-async-http#902] opened 2015-07-09 07:58 UTC
I have two different domain urls named A.com and B.com. This is the code to send request: the asyncHttpClient is the same one.

`asyncHttpClient.post(context, "A.com", aParams, aResponseHandler);`
`asyncHttpClient.post(context, "B.com", bParams, bRsponseHandler);`

There is a chance to happen: get "B.com" response in aResponseHandler, although it doesn't happen frequently. Why does it mistake the response ?

Whether i perform either of them solely, it's ok.
[I find another guy has the same question.](https://github.com/loopj/android-async-http/issues/818)

**Comment by smarek** [comment] 2015-07-12 12:13
Thank you for pointing out, I've never seen this problem in production and I don't have any test-case for it, if you can provide us with test-case, where this problem happens predictably, we can fix that. 
Til then, closing as duplicate to the #818

**Closed by smarek** 2015-07-12 12:13 UTC

**Comment by ff0o0** [comment] 2015-07-13 02:30
@smarek Sorry for provide nothing usefull. Now i doubt that there is something wrong with our server. 
Following is two test domains(different response structure):
|domain|url|response|
|:--:|--|--|
|A|http://api.ktkt.com/|{"code":xx,"data":"xx","message":"xx","status":"xx"}|
|B|http://apit.liangtou.com/|{"info":"xx","data":xx}|

The error(A get the response of B) will happen after requset two url together circularly. Usually it's only need several times.

**Comment by smarek** [comment] 2015-07-13 06:19
@ff0o0 thank you, are we talking about the problem being on `POST` or `GET` or both methods?

**Comment by smarek** [comment] 2015-07-13 06:41
Well, in the meantime, I wrote little test

Basically two separate HttpResponseHandlers, one for each data type, and due to missing annotations, if data from B appeared in rhA or other way around, it will fail.

And indeed, I got a fail, however just once, in the very beginning of test.

Can you please run the same test on your side and provide outputs? @ff0o0 @liumingkong

**LogCat outputs**: http://pastebin.com/Zeff4WpB
**Code** (to compile you need to provide similar [build config](https://github.com/loopj/android-async-http/blob/master/sample/build.gradle))
```java
package com.loopj.android.http.sample;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;

import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.BaseJsonHttpResponseHandler;

import org.apache.http.Header;

public class CycleSample extends Activity {

    private Handler handler = new Handler();
    private AsyncHttpClient ahc = new AsyncHttpClient();
    private final static int INTERVAL = 1000; // 1 second
    private boolean stopCycle = false;

    private final static String URL_A = "http://apit.liangtou.com/";
    private final static String URL_B = "http://api.ktkt.com/";

    private final static class DataA {
        public String version;
        public String ip;
        public long time;
    }

    private final static class ResponseA {
        public String info;
        public DataA data;
    }

    private final static class ResponseB {
        public int code;
        public String data;
        public String message;
        public String status;
    }

    private BaseJsonHttpResponseHandler<ResponseA> rhA = new BaseJsonHttpResponseHandler<ResponseA>() {
        static final String TAG = "RH_A";

        @Override
        public void onSuccess(int statusCode, Header[] headers, String rawJsonResponse, ResponseA response) {
            Log.d(TAG, "ok");
        }

        @Override
        public void onFailure(int statusCode, Header[] headers, Throwable throwable, String rawJsonData, ResponseA errorResponse) {
            Log.e(TAG, "failure", throwable);
        }

        @Override
        protected ResponseA parseResponse(String rawJsonData, boolean isFailure) throws Throwable {
            return new ObjectMapper().readValues(new JsonFactory().createParser(rawJsonData), ResponseA.class).next();
        }
    };
    private BaseJsonHttpResponseHandler<ResponseB> rhB = new BaseJsonHttpResponseHandler<ResponseB>() {
        static final String TAG = "RH_A";

        @Override
        public void onSuccess(int statusCode, Header[] headers, String rawJsonResponse, ResponseB response) {
            Log.d(TAG, "ok");
        }

        @Override
        public void onFailure(int statusCode, Header[] headers, Throwable throwable, String rawJsonData, ResponseB errorResponse) {
            Log.e(TAG, "failure", throwable);
        }

        @Override
        protected ResponseB parseResponse(String rawJsonData, boolean isFailure) throws Throwable {
            return new ObjectMapper().readValues(new JsonFactory().createParser(rawJsonData), ResponseB.class).next();
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ahc.setMaxRetriesAndTimeout(0, 10000);
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                ahc.get(CycleSample.this, URL_A, rhA);
                ahc.get(CycleSample.this, URL_B, rhB);
                if (!stopCycle) {
                    handler.postDelayed(this, 1000);
                }
            }
        }, INTERVAL);
    }

    @Override
    protected void onPause() {
        super.onPause();
        stopCycle = true;
    }

    @Override
    protected void onStop() {
        super.onStop();
        stopCycle = true;
    }
}
```

**Comment by ff0o0** [comment] 2015-07-13 07:38
@smarek both methods. My test log is the same with yours.
```
07-13 15:34:54.864  29848-29848/com.example.gustavo.hello E/RH_A﹕ failure
    com.fasterxml.jackson.databind.RuntimeJsonMappingException: Unrecognized field "code" (class com.example.gustavo.hello.activity.CycleSample$ResponseA), not marked as ignorable (2 known properties: "data", "info"])
            at [Source: {"code":404,"data":null,"message":"访问地址不存在","status":"err"}; line: 1, column: 12] (through reference chain: com.example.gustavo.hello.activity.ResponseA["code"])
            at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:121)
            at com.example.gustavo.hello.activity.CycleSample$1.parseResponse(CycleSample.java:58)
            at com.example.gustavo.hello.activity.CycleSample$1.parseResponse(CycleSample.java:43)
            at com.loopj.android.http.BaseJsonHttpResponseHandler$1.run(BaseJsonHttpResponseHandler.java:82)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "code" (class com.example.gustavo.hello.activity.CycleSample$ResponseA), not marked as ignorable (2 known properties: "data", "info"])
            at [Source: {"code":404,"data":null,"message":"访问地址不存在","status":"err"}; line: 1, column: 12] (through reference chain: com.example.gustavo.hello.activity.ResponseA["code"])
            at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
            at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324)
            at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1302)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:249)
            at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
            at com.fasterxml.jackson.databind.MappingIterator.nextValue(MappingIterator.java:188)
            at com.fasterxml.jackson.databind.MappingIterator.next(MappingIterator.java:119)
            at com.example.gustavo.hello.activity.CycleSample$1.parseResponse(CycleSample.java:58)
            at com.example.gustavo.hello.activity.CycleSample$1.parseResponse(CycleSample.java:43)
            at com.loopj.android.http.BaseJsonHttpResponseHandler$1.run(BaseJsonHttpResponseHandler.java:82)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by smarek** [comment] 2015-07-13 07:42
@ff0o0 on which rate does the exception occur to you? Because so far I was able to get that response like 2 times from overall of roughly 1000 requests

**Comment by ff0o0** [comment] 2015-07-13 07:45
@smarek By comparing my own test code, I wonder using 'TextHttpResponseHandler' instead may increase the rate.

**Comment by smarek** [comment] 2015-07-13 08:51
Haven't been able to reproduce since, even created new test-case using TextHttpResponseHandler, which also heavy-loads the services.

```java
package com.loopj.android.http.sample;

import android.app.Activity;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;

import com.loopj.android.http.AsyncHttpClient;
import com.loopj.android.http.ResponseHandlerInterface;
import com.loopj.android.http.TextHttpResponseHandler;

import org.apache.http.Header;
import org.apache.http.client.HttpResponseException;

public class CycleSample extends Activity {

    private Handler handler = new Handler();
    private AsyncHttpClient ahc = new AsyncHttpClient();
    private final static int INTERVAL = 500; // 1 second
    private boolean stopCycle = false;

    private final static String URL_A = "http://apit.liangtou.com/";
    private final static String URL_B = "http://api.ktkt.com/";

    private final static class DataA {
        public String version;
        public String ip;
        public long time;
    }

    private final static class ResponseA {
        public String info;
        public DataA data;
    }

    private final static class ResponseB {
        public int code;
        public String data;
        public String message;
        public String status;
    }

    private ResponseHandlerInterface rhA = new TextHttpResponseHandler() {
        static final String TAG = "RH_A";

        @Override
        public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
            Log.d(TAG, "failure " + getRequestURI(), (throwable instanceof HttpResponseException) ? null : throwable);
        }

        @Override
        public void onProgress(long bytesWritten, long totalSize) {

        }

        @Override
        public void onSuccess(int statusCode, Header[] headers, String responseString) {
            if (responseString.startsWith("{\"info\":\"ok\""))
                Log.d(TAG, "ok " + responseString + " " + getRequestURI());
            else
                Log.d(TAG, "fatal" + responseString + " " + getRequestURI());
        }
    };
    private ResponseHandlerInterface rhB = new TextHttpResponseHandler() {
        static final String TAG = "RH_B";

        @Override
        public void onFailure(int statusCode, Header[] headers, String responseString, Throwable throwable) {
            Log.d(TAG, "failure " + getRequestURI(), (throwable instanceof HttpResponseException) ? null : throwable);
        }

        @Override
        public void onProgress(long bytesWritten, long totalSize) {

        }

        @Override
        public void onSuccess(int statusCode, Header[] headers, String responseString) {
            if (responseString.startsWith("{\"code\":200"))
                Log.d(TAG, "ok " + responseString + " " + getRequestURI());
            else
                Log.d(TAG, "fatal" + responseString + " " + getRequestURI());
        }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ahc.setMaxRetriesAndTimeout(0, 15000);
        ahc.setEnableRedirects(false, false, false);
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                ahc.get(CycleSample.this, URL_A, rhA);
                ahc.get(CycleSample.this, URL_A, rhA);
                ahc.get(CycleSample.this, URL_B, rhB);
                ahc.get(CycleSample.this, URL_B, rhB);
                ahc.get(CycleSample.this, URL_A, rhA);
                ahc.get(CycleSample.this, URL_B, rhB);
                ahc.get(CycleSample.this, URL_A, rhA);
                ahc.get(CycleSample.this, URL_B, rhB);
                if (!stopCycle) {
                    handler.postDelayed(this, INTERVAL);
                }
            }
        }, INTERVAL);
    }

    @Override
    protected void onPause() {
        super.onPause();
        stopCycle = true;
    }

    @Override
    protected void onStop() {
        super.onStop();
        stopCycle = true;
    }
}
```

**Comment by ff0o0** [comment] 2015-07-14 02:25
@smarek well, maybe there is something wrong with my server...

**Comment by smarek** [comment] 2015-09-14 16:01
Nope, I'm sorry @ff0o0 we've definitely confirmed this as problem of non-thread-safety, see the ticket, where we'll be resolving this #918
