### ISSUE TITLE
Can not support SDK23,can't find org.apache.http.Header

### ISSUE THREAD

**Issue by Modificator** [loopj/android-async-http#925] opened 2015-08-18 06:13 UTC
http://developer.android.com/sdk/api_diff/23/changes.html

**Comment by smarek** [comment] 2015-08-18 06:23
duplicate of #830

**Closed by smarek** 2015-08-18 06:23 UTC

**Comment by Modificator** [comment] 2015-08-18 06:47
How to get it

**Comment by Maheshws** [comment] 2015-08-18 07:49
temporary fix, add this line to gradle:
compile "org.apache.httpcomponents:httpcore:4.3.2"

**Comment by iriki** [comment] 2015-09-30 22:59
Or just use 

android {
    useLibrary 'org.apache.http.legacy'
}

**Comment by smarek** [comment] 2015-10-04 10:51
Don't use `org.apache.http` packaged classes, use `cz.msebera.android.httpclient` package, which is used by this library since 1.4.9 version
