### ISSUE TITLE
org.apache.http.Header Deprecated? Alternate?

### ISSUE THREAD

**Issue by alirizwan** [loopj/android-async-http#920] opened 2015-08-09 22:50 UTC
Hi guys, Http.Header is deprecated in API Level 22. Is there a workaround for this? I am using 1.4.8 of android async http library.

**Comment by smarek** [comment] 2015-08-10 07:36
duplicate of #830 
So far M-Preview didn't remove the runtime, and were working on standalone version built on top of HttpClient 4.3 , with Apache HC team. See #775

**Closed by smarek** 2015-08-10 07:36 UTC

**Comment by Maheshws** [comment] 2015-08-18 07:49
temporary fix, add this line to gradle:
    compile "org.apache.httpcomponents:httpcore:4.3.2"

**Comment by laudarch** [comment] 2015-10-04 01:02
Maheshws is right that temp fix works nicely.

**Comment by smarek** [comment] 2015-10-04 09:04
that's invalid to me, just solving "deprecated" indication on Header in IDE will not use the non-deprecated variant in Android runtime, because you'll be using `org.apache.http.*` classes that are provided by Android runtime, which will override whatever implementation you provide through your APK/JAR build.
see https://github.com/loopj/android-async-http/issues/830 for compatible and library-supported solution

**Comment by laudarch** [comment] 2015-10-04 10:39
As in #830 problem gets solved but with 1.4.9 and 1.5.0 and is a better solution.

**Comment by smarek** [comment] 2015-10-04 10:49
Since 1.4.9 library is using upstream HttpClient which provides non-deprecated classes (those were deprecated only in Android platform), along with packed HttpCore, HttpMime and HttpClient-Cache libraries (see the project for reference https://github.com/smarek/httpclient-android/releases )
