### ISSUE TITLE
How can i know the progress of the upload (post)?

### ISSUE THREAD

**Issue by march1993** [loopj/android-async-http#956] opened 2015-09-10 16:35 UTC
It seems that `onProgress' only shows the download progess?

**Comment by smarek** [comment] 2015-09-11 09:11
Yes, this is known feature, closing as duplicate of #239

**Closed by smarek** 2015-09-11 09:11 UTC

**Comment by march1993** [comment] 2015-09-11 16:59
public void onProgress(long bytesWritten, long totalSize) {
    // Progress notification
    if(totalSize > 4096) {
        Log.d("now: ", bytesWritten.toString();
    }
}
but i get no log

**Comment by smarek** [comment] 2015-09-12 02:07
Again, yes, there is no library provided upload onProgress, just download.

**Comment by march1993** [comment] 2015-09-13 09:02
so sad
