### ISSUE TITLE
Can't receive response for some URLs

### ISSUE THREAD

**Issue by androids-dev** [loopj/android-async-http#907] opened 2015-07-18 14:49 UTC
There has been some issue recently by which I am not able to receive response for some URLs.
Sample code : http://pastebin.com/2YP6rmnf

I am facing this issue since last 2 weeks only. It was working fine before that

[Update link]

**Comment by smarek** [comment] 2015-07-19 18:16
Can you post what is in applications LogCat? Also what version of library do you use? Is it the latest version?

**Comment by androids-dev** [comment] 2015-07-20 05:04
You can find logcat here - http://pastebin.com/y8fYmMJD
I tried on 1.4.8 and 1.4.7

It works fine with OkHttp

**Comment by smarek** [comment] 2015-07-20 10:52
"It works fine with OkHttp" is not a valid argument, as the libraries are based differently
`NoHttpResponseException: The target server failed to respond` means the server didn't respond to the request within given timeout, nothing we should fix on library level in my opinion. Closing the issue, unless you can say more, about why this should be issue of library and not how it is used or the device it is used on. Sorry

**Closed by smarek** 2015-07-20 10:52 UTC
Labels: on hold

**Comment by iandunn** [comment] 2015-07-28 17:45
@smarek, the URL that @androids-dev is having problems with is https://central.wordcamp.org/wp-json/posts?type=wordcamp, which works fine in browsers, curl, etc, so it doesn't seem to be a server-side issue. If you have a few minutes, would you mind testing that URL with the library to see if you can reproduce the error?

**Comment by smarek** [comment] 2015-07-29 17:48
@iandunn no, unless proven as library issue, I'm not going to do your job for free. 
You can try to raise Timeout limits, maybe the problem is that server is not sending the result fast enough.
