### ISSUE TITLE
【v1.4.6】Useless warning  in SyncHttpClient

### ISSUE THREAD

**Issue by diaocow** [loopj/android-async-http#837] opened 2015-04-08 13:34 UTC
When use SyncHttpClient in **individual Thread**（1.4.6）,  i received warnning :
 **Current thread has not called Looper.prepare(). Forcing synchronous mode.**

And I go through the source code to find the reason:

Once I create a responseHandler  it will call  **setUseSynchronousMode(false)** , but because its in a **new thread**， so it's looper is null , and execute this code:

```
@Override
    public void setUseSynchronousMode(boolean sync) {
        // A looper must be prepared before setting asynchronous mode.
        if (!sync && looper == null) {
            sync = true;
            Log.w(LOG_TAG, "Current thread has not called Looper.prepare(). Forcing synchronous mode.");
        }

       ....

        useSynchronousMode = sync;
    }
```

I don't think it's wrong to use SyncHttpClient in this way, Hope to improve warnning message(^_^)， it's sometimes confused.

**Comment by smarek** [comment] 2015-04-09 07:23
Is there any reason, why you opened another ticket?
I'm closing this as duplicate of #828

**Closed by smarek** 2015-04-09 07:23 UTC

**Comment by mpj** [comment] 2015-12-25 23:04
I'm getting this warning too. I'm calling SyncHttpClient inside onRunTask of a GcmTaskService, if that helps debug it. 
Nothing fancy, just a 
SyncHttpClient client = new SyncHttpClient();
ByteArrayEntity entity = // some data
client.post(this, "http://service.com/endpoint", entity, "application/json", resonseHandler)
