### ISSUE TITLE
question about Capturing HTTP Requests with fiddler or Charles 

### ISSUE THREAD

**Issue by s-h-i-tGFW** [loopj/android-async-http#974] opened 2015-09-25 07:35 UTC
After I update my library to latest version,I cat't get data with fiddler,the old version I use 1.4.6 and the new version is 1.4.9.The reason why?

**Comment by lby1992** [comment] 2015-09-25 07:55
I'm sorry, I could't help you.

**Comment by lby1992** [comment] 2015-09-25 08:05
Oh, you may mean the lastest version not the last version?

**Comment by smarek** [comment] 2015-09-25 09:37
Hi, how did you set up Fiddler/Charles before, what now doesn't work? Library only changed underlying version of HttpClient, so there shouldn't be anything different in matter of using network inspection tools.

**Comment by s-h-i-tGFW** [comment] 2015-09-25 09:45
Thanks for your reply ,I trid 1.4.8 demo,it work well. But change to 1.4.9 demo，fiddler can't get data....

**Comment by lby1992** [comment] 2015-09-25 09:48
I think, it may be because of the http version.

**Comment by smarek** [comment] 2015-09-25 09:50
Well you still haven't said how did you setup Fiddler to capture and filter traffic, so it's hard to guess what is your problem. Certainly there is nothing in latest changes in library that should prevent traffic from being captured, unless you, of course, use encrypted traffic and Fiddler doesn't have access to private key of CA/INTERMEDIATE SSL certificate.

**Comment by s-h-i-tGFW** [comment] 2015-09-28 02:20
It's httpclient's change,haven't find the solution...

**Comment by phyllipe** [comment] 2015-10-13 19:44
Same problem for me, I'm using Charles 3.11

**Comment by smarek** [comment] 2015-10-26 20:45
I will solve this, as I'm curious why it suddenly stopped working. Any of you guys are able to provide more debug info on this topic?

**Comment by phyllipe** [comment] 2015-10-27 14:23
Hi ! Thanks a lot for taking care of that issue !
Which kind of debug info can help you for the fix ?

**Comment by smarek** [comment] 2015-10-27 14:25
Since I'm not skilled with neither Fiddler or Charles, if you could provide me with complete setup info so I could reproduce the situation, that would be great!

**Comment by phyllipe** [comment] 2015-10-27 14:56
You can find Charles at this address : 
http://www.charlesproxy.com/download/

There is a trial version, so you don't have to pay for it.
I use the latest version : 3.11.1

Those link can be helpful for setting up Charles :
https://www.charlesproxy.com/documentation/faqs/using-charles-from-an-iphone/
http://codewithchris.com/tutorial-using-charles-proxy-with-your-ios-development-and-http-debugging/

don't hesitate to ask if you have any questions :)

**Comment by smarek** [comment] 2015-10-27 15:21
@phyllipe i've downloaded and ran it, but my firewall didn't detect any attempt to open ports to network, what is specifically your configuration? How do you hook it up on external network interface ? I'm using OSX btw, not sure if that does make big difference

**Comment by phyllipe** [comment] 2015-10-27 15:32
@smarek what do you mean by external network interface ?
basically you have to get your computer's ip address :
![system-preferences-network-settings](https://cloud.githubusercontent.com/assets/1270537/10762819/f18f5654-7c9d-11e5-9db3-421d11cd2944.jpg)

set the http proxy on "manual" and put this ip address in the http proxy server on your device (iPhone or android), the port is 8888 :
![charles-wifi-proxy-settings](https://cloud.githubusercontent.com/assets/1270537/10762847/19d3283e-7c9e-11e5-96d5-0bf2f9107115.jpg)

**Comment by smarek** [comment] 2015-10-27 15:34
I get this part, but when I run Charles on my computer, it doesn't listen on my computer's IP address for incoming connections to proxy them, I thought I'm missing something in configuration.

**Comment by smarek** [comment] 2015-10-27 15:55
Oh, I had to disable a lot of security, then it started working. However I get the problem why it's not catcheable by Charles/Fiddler proxies. HttpClient is not by default configured to use system proxy, which was previously automatic with Android provided version of HttpClient, now it must be configured manually after initialization.

I don't have much more time to invest here, so please try to update your Android-Async-Http library usage to set the Proxy manually, then it should start work automagically.

ie. https://stackoverflow.com/questions/25567973/apache-httpclient-4-3-5-set-proxy

**Comment by Borhan10** [comment] 2015-11-01 12:42
@smarek Do you have any idea how to solve this problem

I do all configuration on fiddler on my Pc and on My android Phone.

The application that I want to catch his request use last loopJ library.

When I make login or any action on my application nothing appear on fiddler.

So is there any solution ?

**Comment by s-h-i-tGFW** [comment] 2015-11-02 06:49
I've no idea,just change my asyncLibrari to 1.4.8

**Comment by smarek** [comment] 2015-11-17 15:57
Closing this issue in favor of solving automatically setting system proxy #971

**Closed by smarek** 2015-11-17 15:57 UTC
Labels: low, question
