### ISSUE TITLE
SNI support

### ISSUE THREAD

**Issue by pratikpradhan** [loopj/android-async-http#1006] opened 2015-10-22 11:53 UTC
Hi,

I am using android-async-http-1.4.9 and it is giving me error for certificate mismatch for https connections. We are using SNI on serverside. I have tried with multiple ssl checker sites and our certificates are installed properly. 

Can you confirm if SNI is supported in the current version?
Is there any android version dependency? Our app supports android 4.1 or greater.

**Comment by sanjayharan** [comment] 2015-10-23 12:18
+1
I'm facing same issue, I'have changes the library,but I didn't get solution from this library.

**Comment by Saren-Arterius** [comment] 2015-11-08 16:47
To test it: https://saren.wtako.net
Since it's using CF free plan, the website should be only working in sni supported clients

**Comment by smarek** [comment] 2015-11-17 16:36
I'm sorry, I thought that implementing upstream version of HttpClient will solve the SNI issue, however I've found several patches that have been done against upstream for Android distribution of HttpClient that allow SNI to work. Will implement this in 1.5 branch
1.4 does not support that now.

**Comment by smarek** [comment] 2015-11-17 16:57
Also closing as duplicate of #991

**Closed by smarek** 2015-11-17 16:57 UTC
Labels: feature-request

**Comment by fipil** [comment] 2016-03-14 08:41
Hi, please is there any planned release date of the branch 1.5? I need the SNI support, so I've to make decission between waiting for the SNI support and moving to different library.
Thanks a lot.
