### ISSUE TITLE
org.apache.http.Header deprecated in API level 22.

### ISSUE THREAD

**Issue by seshuvinay** [loopj/android-async-http#833] opened 2015-03-30 11:36 UTC
This may affect this library in the future.

**Comment by smarek** [comment] 2015-04-02 13:09
Thank you, yes, migration over to HttpClient 4 from Apache HttpComponents team will solve this issue, leaving open until fixed.

**Comment by smarek** [comment] 2015-04-03 13:40
Closing as duplicate of #830

**Closed by smarek** 2015-04-03 13:40 UTC
Labels: moderate
