### ISSUE TITLE
Can not set host in header

### ISSUE THREAD

**Issue by qianjin** [loopj/android-async-http#1000] opened 2015-10-20 08:18 UTC
I user ip-address in my url and need set host in header , but set host in header not work , it is also change the host to ip-address

```java
client.addHeader("Host", "api.myhost.com:8030");
```

but the request atuo change `host` to ip-address:`Host: 123.59.xx.xx:8030`

my request url is like this use ip: 
```java
http://123.59.xx.xx:8030/release/checkupdate
```
I also change host by this code but it is not work,
```java
 HttpHost httpHost = new HttpHost("api.myhost.com",8030);
 client.getHttpContext().setAttribute(ExecutionContext.HTTP_TARGET_HOST, httpHost);
```

use version 1.4.8

**Comment by smarek** [comment] 2015-11-17 16:27
Duplicate of #998

**Closed by smarek** 2015-11-17 16:27 UTC
